const myself = [
    "I'm Hikaro Fernandes de Carvalho, I'm 28 years old. I'm very proactive.  I like a job well done. I'm spontaneous, a bit boring sometimes, but having a little patience, I can handle it. 'HAHAHAHA'!",
    "In my experiences with work. I have some accomplishments such as:",
    'In my first job as a young storekeeper`s apprentice, I managed to reorganize the entire storeroom, carry out all the insertion in the system for more than 3 years of invoices that were stopped. I managed to keep it clean and well organized.“I managed to save the company with parts that I ended up finding while organizing the stock".',
    "In my second job, I performed many appointments during my temporary outsourced contract by the company Adminas for the TRE, where I managed to reduce the queue of people to be served daily, as it turned out to be one of the fastest in the biometric re-registration service for which there was a temporary contract.",
    'In my third service, where I worked as a systems` trainer, I managed to learn the 3 systems that I would have to teach without much help, spending just 1 month. "The company had 6 modules, each module corresponding to a complete application for recording, removing, updating data in addition to generating reports and graphs on the base data it dealt with. (car sales module, financial module, accounting module, sales module parts, tractor sales module)',
    "In my last job where I worked as a Computer Technician, I performed some tasks in addition to the maintenance of servers, networks, and computers, tasks such as helping lawyers in the use of Brazilian court systems and helping with graphic material such as printing, scanning, and photocopying. My achievements in the company were to streamline the service to lawyers, implement a script to clean and shut down machines via the network (the company did not have software for this and so far it was all done manually) where on the 70 machines that existed in the company that was used by lawyers during the day, had their files deleted, and the machine turned off at the end of the day. Another achievement was to seek to learn court systems that did not belong to Goiás, as there were no places to help lawyers who could help them here in Goiás.",
    "Well, in all my work, the only thing that made me sad was the lack of meritocracy. I believe that what makes a job fair is a meritocracy. Someone who is well-regarded for his effort and hard work, not for being nominated by a high-ranking person.",
    "What I believe to be a quality job is precisely a job where the company uses meritocracy as the main idea to treat its employees."
]

export default myself;